name: Release REE.Packer

on:
  push:
    branches: [ main ]

jobs:
  build-and-release:
    runs-on: windows-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Setup MSBuild
      uses: microsoft/setup-msbuild@v2

    - name: Setup NuGet
      uses: NuGet/setup-nuget@v2

    - name: Restore NuGet packages
      run: nuget restore REE.Packer/REE.Packer.sln

    - name: Build solution
      run: msbuild REE.Packer/REE.Packer.sln /p:Configuration=Release

    - name: Zip build output
      run: |
        powershell Compress-Archive -Path REE.Packer/REE.Packer/bin/Release/* -DestinationPath REE.Packer.zip

    - name: Set version
      id: set_version
      run: echo "version=0.0.0.${{ github.run_number }}" >> $GITHUB_ENV

    - name: Create tag
      run: |
        git config --global user.name "github-actions"
        git config --global user.email "github-actions@github.com"
        git tag ${{ env.version }}
        git push origin ${{ env.version }}

    - name: Create GitHub Release
      uses: softprops/action-gh-release@v2
      with:
        tag_name: ${{ env.version }}
        name: REE.Packer ${{ env.version }}
        files: REE.Packer.zip
